# Generated by Django 3.2.12 on 2022-03-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_api', '0007_ethereumaccounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethereumaccounts',
            name='eth_type',
            field=models.CharField(default='mainnet', max_length=50),
            preserve_default=False,
        ),
    ]
